-- MySQL Script generated by MySQL Workbench
-- Tue May 17 20:30:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`WebformDB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`WebformDB` (
  `TextDescription1` VARCHAR(63) NULL,
  `TextAnswer1` VARCHAR(63) NULL,
  `TextDescription2` VARCHAR(63) NULL,
  `TextAnswer2` VARCHAR(63) NULL,
  `ButtonDescription1` VARCHAR(63) NULL,
  `ButtonAnswer1` TINYINT NULL,
  `ButtonDescription2` VARCHAR(63) NULL,
  `ButtonAnswer2` TINYINT NULL,
  `FileUploadDescription1` VARCHAR(63) NULL,
  `FileUploadAnswer1` LONGBLOB NULL,
  `FileUploadDescription2` VARCHAR(63) NULL,
  `FileUploadAnswer2` LONGBLOB NULL,
  `LongTextDescription1` VARCHAR(63) NULL,
  `LongTextAnswer1` VARCHAR(511) NULL,
  `LongTextDescription2` VARCHAR(63) NULL,
  `LongTextAnswer2` VARCHAR(511) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
